

spring:
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:system
    username: sa
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate.globally_quoted_identifiers: true
      hibernate.format_sql: true
    open-in-view: false
    #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  authentication:
    key: A534BDSF43353666AJHREDVH5673434645
server:
  port: 8099
  error:
    include-stacktrace: never